services:
  database:
    image: postgres:15.4-alpine
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /bot_data:/var/lib/postgresql/data

  bot:
    depends_on:
      database:
        condition: service_healthy
    build: .
    env_file:
      - .env
