"""add_responses

Revision ID: c4d047a29129
Revises: 1617f17207f2
Create Date: 2023-09-08 01:03:03.708218

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c4d047a29129"
down_revision = "1617f17207f2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "responses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_responses_id"), "responses", ["id"], unique=False)
    op.create_index(op.f("ix_responses_text"), "responses", ["text"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_responses_text"), table_name="responses")
    op.drop_index(op.f("ix_responses_id"), table_name="responses")
    op.drop_table("responses")
    # ### end Alembic commands ###
