"""date

Revision ID: 1617f17207f2
Revises: 165592526aa1
Create Date: 2023-09-07 23:52:13.098421

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1617f17207f2"
down_revision = "165592526aa1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("date", sa.DateTime(), nullable=False))
    op.create_index(op.f("ix_messages_date"), "messages", ["date"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_messages_date"), table_name="messages")
    op.drop_column("messages", "date")
    # ### end Alembic commands ###
